# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  test:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24
          gateway: 172.21.0.1

services:

  ca_org1:
    user: ${CNTR_USER_ID}:${CNTR_USER_GRP}
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054

      #pkcs11
      - FABRIC_CA_SERVER_DEBUG=true
      - FABRIC_CA_SERVER_BCCSP_DEFAULT=PKCS11
      - FABRIC_CA_SERVER_BCCSP_PKCS11_LIBRARY=/usr/local/lib/softhsm/libsofthsm2.so
      - FABRIC_CA_SERVER_BCCSP_PKCS11_PIN=98765432
      - FABRIC_CA_SERVER_BCCSP_PKCS11_LABEL=ForFabric
      - FABRIC_CA_SERVER_BCCSP_PKCS11_HASH=SHA2
      - FABRIC_CA_SERVER_BCCSP_PKCS11_SECURITY=256
      # uncomment to manually import ca-root key/cert
      #- FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server/ca.example.com-cert.pem
      #- FABRIC_CA_SERVER_CA_KEYFILE=
      - SOFTHSM2_CONF=/tmp/softhsm2.conf

    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    #command: sh -c "sleep 99999"
    volumes:
      - ../organizations/fabric-ca/org1:/etc/hyperledger/fabric-ca-server

      #pkcs11
      - ../_pkcs_data/docker/ca_org1/vol/fabric-ca-server/fabric-ca-server-config.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
      - ../_pkcs_data/softhsm/tokens/:/tmp/tokens/

      #fabric-ca-2.0.0-alpha: alpine 3.9.6 
      - ../_pkcs_in/docker/alpine/3.9.6/softhsm/:/usr/local/lib/softhsm/
      - ../_pkcs_in/docker/alpine/3.9.6/softhsm2.conf:/tmp/softhsm2.conf
      - ../_pkcs_in/docker/alpine/3.9.6/usr/lib/libgcc_s.so.1:/usr/lib/libgcc_s.so.1
      - ../_pkcs_in/docker/alpine/3.9.6/usr/lib/libstdc++.so.6:/usr/lib/libstdc++.so.6
      - ../_pkcs_in/docker/alpine/3.9.6/usr/lib/libstdc++.so.6.0.25:/usr/lib/libstdc++.so.6.0.25
            
    container_name: ca_org1
    networks:
      - test

  ca_org2:
    user: ${CNTR_USER_ID}:${CNTR_USER_GRP}
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8054

      #pkcs11
      - FABRIC_CA_SERVER_DEBUG=true
      - FABRIC_CA_SERVER_BCCSP_DEFAULT=PKCS11
      - FABRIC_CA_SERVER_BCCSP_PKCS11_LIBRARY=/usr/local/lib/softhsm/libsofthsm2.so
      - FABRIC_CA_SERVER_BCCSP_PKCS11_PIN=98765432
      - FABRIC_CA_SERVER_BCCSP_PKCS11_LABEL=ForFabric
      - FABRIC_CA_SERVER_BCCSP_PKCS11_HASH=SHA2
      - FABRIC_CA_SERVER_BCCSP_PKCS11_SECURITY=256
      # uncomment to manually import ca-root key/cert
      #- FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server/ca.example.com-cert.pem
      #- FABRIC_CA_SERVER_CA_KEYFILE=
      - SOFTHSM2_CONF=/tmp/softhsm2.conf

    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    #command: sh -c "sleep 99999"

    volumes:
      - ../organizations/fabric-ca/org2:/etc/hyperledger/fabric-ca-server

      #pkcs11
      - ../_pkcs_data/docker/ca_org2/vol/fabric-ca-server/fabric-ca-server-config.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
      - ../_pkcs_data/softhsm/tokens/:/tmp/tokens

      #fabric-ca-2.0.0-alpha: alpine 3.9.6 
      - ../_pkcs_in/docker/alpine/3.9.6/softhsm/:/usr/local/lib/softhsm/
      - ../_pkcs_in/docker/alpine/3.9.6/softhsm2.conf:/tmp/softhsm2.conf
      - ../_pkcs_in/docker/alpine/3.9.6/usr/lib/libgcc_s.so.1:/usr/lib/libgcc_s.so.1
      - ../_pkcs_in/docker/alpine/3.9.6/usr/lib/libstdc++.so.6:/usr/lib/libstdc++.so.6
      - ../_pkcs_in/docker/alpine/3.9.6/usr/lib/libstdc++.so.6.0.25:/usr/lib/libstdc++.so.6.0.25

    container_name: ca_org2
    networks:
      - test

  ca_orderer:
    user: ${CNTR_USER_ID}:${CNTR_USER_GRP}
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-orderer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=9054

      #pkcs11
      - FABRIC_CA_SERVER_DEBUG=true
      - FABRIC_CA_SERVER_BCCSP_DEFAULT=PKCS11
      - FABRIC_CA_SERVER_BCCSP_PKCS11_LIBRARY=/usr/local/lib/softhsm/libsofthsm2.so
      - FABRIC_CA_SERVER_BCCSP_PKCS11_PIN=98765432
      - FABRIC_CA_SERVER_BCCSP_PKCS11_LABEL=ForFabric
      - FABRIC_CA_SERVER_BCCSP_PKCS11_HASH=SHA2
      - FABRIC_CA_SERVER_BCCSP_PKCS11_SECURITY=256
      # uncomment to manually import ca-root key/cert
      #- FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server/ca.example.com-cert.pem
      #- FABRIC_CA_SERVER_CA_KEYFILE=
      - SOFTHSM2_CONF=/tmp/softhsm2.conf

    ports:
      - "9054:9054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    #command: sh -c "sleep 99999"
    volumes:
      - ../organizations/fabric-ca/ordererOrg:/etc/hyperledger/fabric-ca-server

      #pkcs11
      - ../_pkcs_data/docker/ca_orderer/vol/fabric-ca-server/fabric-ca-server-config.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
      - ../_pkcs_data/softhsm/tokens/:/tmp/tokens

      #fabric-ca-2.0.0-alpha: alpine 3.9.6 
      - ../_pkcs_in/docker/alpine/3.9.6/softhsm/:/usr/local/lib/softhsm/
      - ../_pkcs_in/docker/alpine/3.9.6/softhsm2.conf:/tmp/softhsm2.conf
      - ../_pkcs_in/docker/alpine/3.9.6/usr/lib/libgcc_s.so.1:/usr/lib/libgcc_s.so.1
      - ../_pkcs_in/docker/alpine/3.9.6/usr/lib/libstdc++.so.6:/usr/lib/libstdc++.so.6
      - ../_pkcs_in/docker/alpine/3.9.6/usr/lib/libstdc++.so.6.0.25:/usr/lib/libstdc++.so.6.0.25

    container_name: ca_orderer
    networks:
      - test
